### ISSUE TITLE
High Severity Vulnerabilities Found 

### ISSUE THREAD

**Issue by nicholascelestin** [paketo-buildpacks/full-stack-release#173]
Resulting image failed an ECR clair Vulnerability scan due to a High severity vulnerability (CVE-2021-44142).

https://ubuntu.com/security/notices/USN-5260-2

What were you attempting to do?
Build an image with 'mvn spring-boot:build-image', referencing 'gcr.io/paketo-buildpacks/builder:full-cf' and scan it with AWS Clair in ECR.

What did you expect to happen?
Find no High level vulnerabilities

What was the actual behavior? Please provide log output, if possible.
Found high level vulnerabilities.

Build Configuration
Using 'mvn spring-boot:build-image', referencing 'gcr.io/paketo-buildpacks/builder:full-cf'.

Additional Notes
This happened once before (to my knowledge) here: https://github.com/paketo-buildpacks/full-stack-release/issues/83
A follow up issue was opened to find out why paketo isn't properly auto-patching based on Ubuntu USNs, but I don't believe there was any resolution: https://github.com/paketo-buildpacks/stacks/issues/75

**Comment by sophiewigmore** [comment]
Hi @nicholascelestin thank you for reaching out! It looks like our automation [picked up this USN](https://github.com/paketo-buildpacks/stack-usns/commit/9ed474beace8db70b4e1230d96bb3fe3bb36cfa9), but the only affected package that Ubuntu reported was `samba`, which isn't on the list of packages in the Full stack ([here](https://github.com/paketo-buildpacks/full-stack-release/blob/main/build-receipt) and [here](https://github.com/paketo-buildpacks/full-stack-release/blob/main/run-receipt)). Because of that no update was issued for it

**Comment by sophiewigmore** [comment]
The most up-to-date version of the stack is v1.3.15. Is that the version you are currently using?

**Comment by nicholascelestin** [comment]
Thanks for your quick response!

I am using mvn spring-boot:build-image, which references the builder at gcr.io/paketo-buildpacks/builder:full-cf . Here is some log output of the build that appears to have more version information:
[logs-of-build-that-failed-scan.log](https://github.com/paketo-buildpacks/full-stack-release/files/7981986/logs-of-build-that-failed-scan.log)

While I am a bit out of my depth with how the Paketo automation works, it does look like the list of packages does contain a reference to 'libwbclient0:amd64 2:4.7.6+dfsg~ubuntu-0ubuntu2.27  - amd64 -  Samba winbind client library', and the 'related notices' section of the [USN page](https://ubuntu.com/security/notices/USN-5260-2) does mention that library in reference to the [CVE](https://ubuntu.com/security/CVE-2021-44142).

Could it be that whatever USN feed kicks off the automated patching workflow is somehow faulty or incomplete?

**Comment by sophiewigmore** [comment]
Yes, you're right that the `'libwbclient0:amd64` is a related package, but it's not clear to me that it's a package directly affected by CVE-2021-44142, if you see what I mean. I don't actually know specifically if it's vulnerable as a result of the `samba` vulnerability. Sometimes the "related" packages are affected, and sometimes they are not. If it is affected, then we definitely need to investigate a better way to include those types of scenarios in our patch updates. 

You're correct that the feed we query might not fully satisfy every case, and we should take a look at it. As for this specific version, I will make sure the new version of `libwbclient0` is pulled into the stack and released.

**Comment by nicholascelestin** [comment]
Yup, I see what you mean. It's not obvious from the Ubuntu website what specific packages are actually vulnerable. And thanks, I'll keep an eye out for that release.

One approach could be to auto-patch all packages whenever a USN happens, rather than having the USN tell you which packages to patch. Perhaps using something like this as a reference: https://packages.ubuntu.com/bionic/allpackages?format=txt.gz .

A different angle would be to incorporate vulnerability scanning into the automation process. For every USN / PR / etc you could build an image and scan it with Trivy. Failures could result in the creation of GitHub issues, the rejection of PRs, etc.

**Comment by sophiewigmore** [comment]
@nicholascelestin it's been released as version [1.3.16](https://github.com/paketo-buildpacks/full-stack-release/releases/tag/1.3.16). Let me know if this clears your vulnerability scan and we can close this issue out. Since our automation looks for updates for packages (separately from USN-related updates) everyday, this shouldn't have been an issue past when that job ran.

Thank you for the suggestions to new approaches, they're much appreciated. Issue https://github.com/paketo-buildpacks/stacks/issues/107 has been opened to investigate modifying our package discovery with some of your suggestions in the future.

**Comment by nicholascelestin** [comment]
Thanks, @sophiewigmore! This does clear up the vulnerability as far as Trivy is concerned. AWS' implementation of Clair, however, is still (seemingly incorrectly) marking the package as having a High vulnerability, despite it being the patched version of samba:2:4.7.6+dfsg~ubuntu-0ubuntu2.28. Not sure what's going on there, but I'll bring it up with AWS support and close out this ticket.
